spring:
  profiles:
    active: default
  application:
    name: @project.name@
  jackson:
    default-property-inclusion: non_null

## Info
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

---
spring:
  profiles: dev
  data:
    mongodb:
      database: keepcalm-foods
      port: 32768
---
spring:
  profiles: azure
  data:
    mongodb:
      database: keepcalm
      port: 10255
      uri: mongodb://keepcalm:axJEXiv9JFiyPzHKY8hufzjyeRpGwzUuBJY0DJWk6oinNyoJdQKs614dqoczF3EHawPctnamdeGDpCwg0UbS0w==@keepcalm.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
