spring:
  application:
    name: @project.name@
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      database: keepcalm
      port: 10255
      uri: mongodb://${mongo.user}:${mongo.password}@${mongo.host}


info:
  profile : ${spring.profiles.active}
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

---
spring:
  profiles: dev
  data:
    mongodb:
      database: keepcalm-foods
      port: 32768
