apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
data:
  username: a2VlcGNhbG0K
  password: YXhKRVhpdjlKRml5UHpIS1k4aHVmemp5ZVJwR3d6VXVCSlkwREpXazZvaW5OeW9KZFFLczYxNGRxb2N6RjNFSGF3UGN0bmFtZGVHRHBDd2cwVWJTMHc9PQo=
