apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keepcalm-food
  labels:
    app: keepcalm-food
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keepcalm-food
        tier: backend
    spec:
      containers:
        - image: keepcalmregistry.azurecr.io/keepcalm-food:v2
          name: keepcalm-food
          env:
            - name: SPRING_PROFILE
              value: "mlab"
            - name: MONGO_DATABASE
              value: "keepcalm-foods"
            - name: MONGO_HOST
              value: "ds147454.mlab.com"
            - name: MONGO_PORT
              value: "47454"
            - name: MONGO_USER
              value: "mongoDbUser"
            - name: MONGO_PASSWORD
              value: "EWjELjkj%HT]DmzkREwMEpMsGK%"
          ports:
            - containerPort: 8080
