apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keepcalm-food
  labels:
    app: keepcalm-food
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keepcalm-food
        tier: backend
    spec:
      containers:
        - image: keepcalmregistry.azurecr.io/keepcalm-food:latest
          name: keepcalm-food
          env:
            - name: SPRING_PROFILE
              value: "azure"
            - name: MONGO_DATABASE
              value : "keepcalm"
            - name: MONGO_HOST
              value: "keepcalm.documents.azure.com"
            - name: MONGO_PORT
              value: "10255"
            - name: MONGO_USER
              value: "keepcalm"
            - name: MONGO_PASSWORD
              value: "axJEXiv9JFiyPzHKY8hufzjyeRpGwzUuBJY0DJWk6oinNyoJdQKs614dqoczF3EHawPctnamdeGDpCwg0UbS0w=="
          ports:
            - containerPort: 8080