apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keepcalm-food
  labels:
    app: keepcalm-food
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keepcalm-food
        tier: backend
    spec:
      containers:
        - image: keepcalmregistry.azurecr.io/keepcalm-food:v2
          name: keepcalm-food
          env:
            - name: MONGO_HOST
              value: "ds147454.mlab.com:47454"
            - name: MONGO_USER
              value: "keepcalmdbuser"
            - name: MONGO_PASSWORD
              value: "Welcome1_"
          ports:
            - containerPort: 8080


#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: account-database
#  labels:
#    app: office-space
#spec:
#  ports:
#    - port: 3306
#      protocol: TCP
#      targetPort: 3306
#  selector:
#    app: office-space
#    tier: database
#---



#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: keepcalm-food-deployment
#spec:
#  selector:
#    matchLabels:
#      app: keepcalm-food
#  replicas: 2 # tells deployment to run 2 pods matching the template
#  template: # create pods using pod definition in this template
#    metadata:
#      labels:
#        app: keepcalm-food
#    spec:
#      containers:
#      - name: keepcalm-food
#        image: keepcalmregistry.azurecr.io/keepcalm-food
#        ports:
#        - containerPort: 8080
