apiVersion: v1
kind: Pod

metadata:
  name: keepcalm-food-azure-pod
  labels:
    app: keepcalm-food
spec:
  containers:
  - image: keepcalmregistry.azurecr.io/keepcalm-food:latest
    name: keepcalm-food

    env:
     - name: MONGO_USER
       valueFrom:
         secretKeyRef:
           name: azure-secret
           key: username
     - name: MONGO_PASSWORD
       valueFrom:
         secretKeyRef:
           name: azure-secret
           key: password
     - name: SPRING_PROFILE
       value: "azure"
     - name: MONGO_DATABASE
       value: "keepcalm"
     - name: MONGO_HOST
       value: "keepcalm.documents.azure.com"
     - name: MONGO_PORT
       value: "10255"


    ports:
      - containerPort: 8080